[programs.localnet]
myepicproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nestoredduardo/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 

[test]
startup_wait = 100000
